# Kustomization file for Emma CSI Driver deployment
# 
# To deploy the Emma CSI Driver using kustomize:
#   kubectl apply -k deploy/
#
# Or to deploy individual manifests:
#   kubectl apply -f deploy/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - csidriver.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - controller.yaml
  - node.yaml
  - storageclass.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: emma-csi-driver
  app.kubernetes.io/component: csi-driver
  app.kubernetes.io/part-of: emma-storage
