apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "emma-csi-driver.fullname" . }}-controller
  labels:
    {{- include "emma-csi-driver.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "emma-csi-driver.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "emma-csi-driver.controller.serviceAccountName" . }}
    namespace: {{ include "emma-csi-driver.namespace" . }}
