{{- if .Values.node.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "emma-csi-driver.node.serviceAccountName" . }}
  namespace: {{ include "emma-csi-driver.namespace" . }}
  labels:
    {{- include "emma-csi-driver.node.labels" . | nindent 4 }}
  {{- with .Values.node.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
