{{- if not .Values.emma.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emma-csi-driver.secretName" . }}
  namespace: {{ include "emma-csi-driver.namespace" . }}
  labels:
    {{- include "emma-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  client-id: {{ required "emma.credentials.clientId is required" .Values.emma.credentials.clientId | quote }}
  client-secret: {{ required "emma.credentials.clientSecret is required" .Values.emma.credentials.clientSecret | quote }}
{{- end }}
