{{- if .Values.storageClasses.create }}
{{- range .Values.storageClasses.classes }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  labels:
    {{- include "emma-csi-driver.labels" $ | nindent 4 }}
  annotations:
    {{- if and (eq .name $.Values.storageClasses.default) .default }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    {{- with $.Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: {{ $.Values.csiDriver.name }}
parameters:
  {{- range $key, $value := .parameters }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .dataCenterId }}
  dataCenterId: {{ .dataCenterId | quote }}
  {{- else if $.Values.emma.defaultDatacenterId }}
  dataCenterId: {{ $.Values.emma.defaultDatacenterId | quote }}
  {{- end }}
reclaimPolicy: {{ .reclaimPolicy }}
volumeBindingMode: {{ .volumeBindingMode }}
allowVolumeExpansion: {{ .allowVolumeExpansion }}
{{- end }}
{{- end }}
